#!/usr/bin/python3
# -*- coding: UTF-8 -*-
import os
print('正在下载Joplin...')
act='wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash'
os.system(act)
print('下载完毕！')