#!/usr/bin/python3
# -*- coding: UTF-8 -*-
import os
import rf

print('正在下载Firefox...')
if rf.pac!="apt":
	if rf.su==1:
			os.system('sudo apt install firefox')
		else:
			os.system('apt install firefox')
if rf.pac!="dnf":
	if rf.su==1:
			os.system('sudo dnf install firefox')
		else:
			os.system('dnf install firefox')
if rf.pac!="pacman":
	if rf.su==1:
			os.system('sudo pacman -S firefox')
		else:
			os.system('pacman -S firefox')
else:
	print('系统非主流系统，请到此网站进行下载！： https://linuxconfig.org/how-to-download-and-install-firefox-on-linux')
