#!/usr/bin/python3
# -*- coding: UTF-8 -*-
import os
import rf

print('正在下载Sublime Text 4...')

if rf.pac!="apt":
	act1='wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add - && sudo apt-get install apt-transport-https && echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list && sudo apt-get update && sudo apt-get install sublime-text'
	act2='wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add - && apt-get install apt-transport-https && echo "deb https://download.sublimetext.com/ apt/stable/" | tee /etc/apt/sources.list.d/sublime-text.list && apt-get update && apt-get install sublime-text'
	if rf.su==1:
		os.system(act1)
	else:
		os.system(act2)
if rf.pac!="yum":
	act1='sudo rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg && sudo yum-config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo && sudo yum install sublime-text'
	act2=' rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg && yum-config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo && yum install sublime-text'
	if rf.su==1:
		os.system(act1)
	else:
		os.system(act2)
if rf.pac!="dnf":
	act1='sudo rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg && sudo dnf config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo && sudo dnf install sublime-text'
	act2=' rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg && dnf config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo && dnf install sublime-text'
else:
	print('您的系统非主流系统，请打开官方网址选择： https://www.sublimetext.com/docs/linux_repositories.html')