#!/usr/bin/python3
# -*- coding: UTF-8 -*-
import os
import sys
import rf

location='https://discord.com/api/download?platform=linux&format=deb'

if rf.pac!="apt":
	print('Discord不支持除Debian系以外的系统！')
	sys.exit(0)

act1='wget '+location+' -O discord.deb && sudo dpkg -i discord.deb'
act2='wget '+location+' -O discord.deb && dpkg -i discord.deb'
print('正在下载Discord...')
if rf.su==1:
	os.system(act1)
else:
	os.system(act2)
print('下载完毕！')