#!/usr/bin/python3
# -*- coding: UTF-8 -*-
import os

location='https://down.qq.com/qqweb/LinuxQQ/linuxqq_2.0.0-b2-1089_x86_64.sh'
print('安装QQ不可避免地需要root权限，是否继续？')
choose=input('y/n:')
if choose=='y':
	print('正在下载QQ...')
	act='wget '+location+' -O qq.sh &&  sudo ./qq.sh'
	os.system(act)
else:
	print('安装取消！')